create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) > 0),
  category text not null check (length(trim(category)) > 0),
  category_order integer not null default 0 check (category_order >= 0),
  text text not null check (length(trim(text)) > 0),
  author text not null check (length(trim(author)) > 0),
  author_id uuid references public.users(id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists documents_public_listing_idx
  on public.documents (category_order, category, date desc, id desc)
  where status = 'published';

create index if not exists documents_author_id_idx
  on public.documents (author_id);

alter table public.documents enable row level security;

comment on table public.documents is
  'CMS-managed documents displayed on the public Documents page.';
comment on column public.documents.category is
  'Section heading used to group documents on the public page.';
comment on column public.documents.category_order is
  'Ordinal position of the category section on the public page.';
